-- NOTE: Database schema is generated via Drizzle ORM.
-- This file is intentionally kept minimal to avoid manual drift.
--
-- Source of truth:
--   - src/db/schema.ts (Drizzle schema definitions)
--
-- Generate SQL (example):
--   - npx drizzle-kit generate
--
-- Then apply migrations to Supabase (recommended):
--   - supabase db push (or run the generated SQL in Supabase SQL editor)
